name: Publish Website

on:
  push:
    branches: # triggers on any push to master
    - Tailwind

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Node.js 14
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm i
    - name: Test
      run: npm run test --if-present
    - name: Build
      run: npm run build --if-present
    - name: Create CNAME
      run: echo "tcukawi.tech" > "dist/CNAME"
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
